% verify_submission.m
% SentinelCrypto - Final MathWorks Submission Verification Engine
%
% This script provides a 1-click verification of the entire repository.
% It tests system health, runs the test suite, generates performance 
% reports, tests UI rendering, and outputs FINAL_SUBMISSION_REPORT.md

function verify_submission()
    clc;
    disp('======================================================');
    disp('    SentinelCrypto MathWorks Submission Verifier      ');
    disp('======================================================');
    disp('Initializing 1-click verification sequence...');
    
    addpath(genpath('src'));
    addpath('tests');
    
    totalScore = 100;
    
    %% 1. System Health Check
    disp('[1/6] Running System Health Checks...');
    healthStatus = SystemHealthCheck.runChecks();
    if strcmp(healthStatus.MATLAB, 'FAIL') || strcmp(healthStatus.Python, 'FAIL')
        healthScore = 'FAIL';
        totalScore = totalScore - 20;
    else
        healthScore = 'PASS';
    end
    
    %% 2. Repository Audit (checkcode)
    disp('[2/6] Running Repository Audit (MATLAB Code Analyzer)...');
    repoScore = SystemHealthCheck.generateRepositoryHealthReport();
    if repoScore > 90
        auditStatus = 'PASS';
    else
        auditStatus = 'WARNING';
        totalScore = totalScore - (100 - repoScore);
    end
    
    %% 3. Unit & Integration Tests
    disp('[3/6] Running Test Suite...');
    try
        testResult = run_all_tests();
        if testResult
            testStatus = 'PASS';
        else
            testStatus = 'FAIL';
            totalScore = totalScore - 30;
        end
    catch ME
        disp(['Test Suite Error: ', ME.message]);
        testStatus = 'FAIL';
        totalScore = totalScore - 30;
    end
    
    %% 4. Prediction Visualizer Render Test
    disp('[4/6] Verifying Prediction UI Rendering & Exporting...');
    try
        test_prediction_render();
        uiStatus = 'PASS';
        pause(2); % Allow UI to render and export before closing
        close all;
    catch ME
        disp(['UI Render Error: ', ME.message]);
        uiStatus = 'FAIL';
        totalScore = totalScore - 20;
    end
    
    %% 5. Generating Reports
    disp('[5/6] Generating Synthetic Forecast Accuracy Report...');
    try
        fg = ForecastReportGenerator();
        % Synthetic history for report generation
        hist = table([1;2;3], [50000;51000;52000], [50100;51500;51800], 'VariableNames', {'Time', 'ActualClose', 'Prediction'});
        report = fg.evaluateHistory(hist);
        fg.generateHTML(report, 'reports/ForecastReport.html');
        reportStatus = 'PASS';
    catch ME
        disp(['Report Gen Error: ', ME.message]);
        reportStatus = 'FAIL';
    end
    
    %% 6. Final Report Generation
    disp('[6/6] Generating FINAL_SUBMISSION_REPORT.md...');
    
    totalScore = max(0, min(100, totalScore));
    
    fid = fopen('FINAL_SUBMISSION_REPORT.md', 'w');
    fprintf(fid, '# Final Submission Report\n\n');
    fprintf(fid, 'Generated by `verify_submission.m` on %s\n\n', datestr(now, 'yyyy-mm-dd HH:MM:SS'));
    fprintf(fid, '## Automated Verification Results\n\n');
    fprintf(fid, '| Metric | Status |\n');
    fprintf(fid, '|---|---|\n');
    fprintf(fid, '| **Repository Health** | %s |\n', healthScore);
    fprintf(fid, '| **Code Audit (checkcode)** | %s (Score: %.1f/100) |\n', auditStatus, repoScore);
    fprintf(fid, '| **Testing Suite** | %s |\n', testStatus);
    fprintf(fid, '| **Prediction UI & Visualization** | %s |\n', uiStatus);
    fprintf(fid, '| **Report Generation** | %s |\n', reportStatus);
    fprintf(fid, '\n');
    
    fprintf(fid, '### Overall Submission Score: %.1f / 100\n\n', totalScore);
    
    if totalScore >= 95
        fprintf(fid, '✅ **Status: SUBMISSION READY (GREEN)**\n');
    else
        fprintf(fid, '❌ **Status: NEEDS WORK (RED)**\n');
    end
    
    fclose(fid);
    
    disp('======================================================');
    disp(' Verification Complete! See FINAL_SUBMISSION_REPORT.md ');
    disp('======================================================');
end
