# db_insert.py
# KCryptoX8 Database Insertion Engine
# Reads the JSON files generated by fetch_free_data.py and saves them to PostgreSQL.

import os
import json
from datetime import datetime
import sys

# Try importing psycopg2, if missing, print user instructions
try:
    import psycopg2
    from psycopg2.extras import execute_values
except ImportError:
    print("❌ Error: psycopg2 is not installed.")
    print("💡 Please install psycopg2-binary using your terminal:")
    print("   pip install psycopg2-binary")
    sys.exit(1)

def load_env_variables(filepath=".env"):
    """Manually parse .env file to extract database credentials"""
    env = {}
    if os.path.exists(filepath):
        with open(filepath, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, val = line.split("=", 1)
                    env[key.strip()] = val.strip()
    return env

def insert_prices(conn, prices):
    """Inserts price data into historical_prices table"""
    if not prices:
        print("⚠️ No price data to insert.")
        return
        
    cursor = conn.cursor()
    query = """
        INSERT INTO historical_prices (timestamp, symbol, open_price, high_price, low_price, close_price, volume)
        VALUES %s
        ON CONFLICT (timestamp, symbol) DO NOTHING;
    """
    
    # Prepare tuples
    records = [
        (p["timestamp"], p["symbol"], p["open"], p["high"], p["low"], p["close"], p["volume"])
        for p in prices
    ]
    
    try:
        execute_values(cursor, query, records)
        conn.commit()
        print(f"✅ Successfully inserted/updated {len(records)} price rows in PostgreSQL.")
    except Exception as e:
        conn.rollback()
        print(f"❌ Error inserting prices into database: {e}")
    finally:
        cursor.close()

def insert_feeds(conn, feeds):
    """Inserts news/feed articles into social_feeds table"""
    if not feeds:
        print("⚠️ No social feeds to insert.")
        return
        
    cursor = conn.cursor()
    query = """
        INSERT INTO social_feeds (timestamp, source, text_content)
        VALUES %s;
    """
    
    # Prepare tuples
    records = [
        (f["timestamp"], f["source"], f["text"])
        for f in feeds
    ]
    
    try:
        execute_values(cursor, query, records)
        conn.commit()
        print(f"✅ Successfully inserted {len(records)} social feed rows in PostgreSQL.")
    except Exception as e:
        conn.rollback()
        print(f"❌ Error inserting social feeds into database: {e}")
    finally:
        cursor.close()

def main():
    # Load settings from .env file
    env = load_env_variables()
    db_host = env.get("DB_HOST", "localhost")
    db_port = env.get("DB_PORT", "5432")
    db_name = env.get("DB_NAME", "kcryptox8")
    db_user = env.get("DB_USER", "postgres")
    db_password = env.get("DB_PASSWORD", "postgres")
    
    # Connect to PostgreSQL
    print(f"🔌 Connecting to PostgreSQL database '{db_name}' on {db_host}:{db_port}...")
    try:
        conn = psycopg2.connect(
            host=db_host,
            port=db_port,
            database=db_name,
            user=db_user,
            password=db_password
        )
    except Exception as e:
        print(f"❌ Database connection failed: {e}")
        print("💡 Make sure you created the database and configured the correct password in '.env'")
        sys.exit(1)
        
    # Read temp JSON files
    try:
        with open("temp_data/binance_prices.json", "r") as f:
            prices = json.load(f)
        with open("temp_data/rss_feeds.json", "r") as f:
            feeds = json.load(f)
    except Exception as e:
        print(f"❌ Failed to load local JSON files: {e}. Please run fetch_free_data.py first.")
        conn.close()
        sys.exit(1)
        
    # Insert data
    insert_prices(conn, prices)
    insert_feeds(conn, feeds)
    
    conn.close()
    print("🔌 Database connection closed.")

if __name__ == "__main__":
    main()
