% generate_project_statistics.m
% Auto-generates PROJECT_STATISTICS.md for the root directory

function generate_project_statistics()
    disp('Generating Project Statistics...');
    
    % Core counts
    mFiles = dir('**/*.m');
    pyFiles = dir('**/*.py');
    csvFiles = dir('**/*.csv');
    htmlFiles = dir('**/*.html');
    mdFiles = dir('**/*.md');
    matFiles = dir('**/*.mat');
    
    totalMLines = 0;
    for i = 1:length(mFiles)
        try
            str = fileread(fullfile(mFiles(i).folder, mFiles(i).name));
            totalMLines = totalMLines + length(regexp(str, '\n')) + 1;
        catch
        end
    end
    
    numMFiles = length(mFiles);
    numPyFiles = length(pyFiles);
    numCsvFiles = length(csvFiles);
    numHtmlFiles = length(htmlFiles);
    numMdFiles = length(mdFiles);
    numModels = length(matFiles);
    
    fid = fopen('PROJECT_STATISTICS.md', 'w');
    fprintf(fid, '# Project Statistics\n\n');
    fprintf(fid, 'This document is automatically generated by `scripts/generate_project_statistics.m`.\n\n');
    fprintf(fid, '| Metric | Count |\n');
    fprintf(fid, '|---|---|\n');
    fprintf(fid, '| MATLAB Files (`.m`) | %d |\n', numMFiles);
    fprintf(fid, '| Python Files (`.py`) | %d |\n', numPyFiles);
    fprintf(fid, '| Lines of MATLAB Code | ~%d |\n', totalMLines);
    fprintf(fid, '| Datasets (`.csv`) | %d |\n', numCsvFiles);
    fprintf(fid, '| Saved Models (`.mat`) | %d |\n', numModels);
    fprintf(fid, '| HTML Reports (`.html`) | %d |\n', numHtmlFiles);
    fprintf(fid, '| Markdown Documentation (`.md`) | %d |\n', numMdFiles);
    
    fprintf(fid, '\n## Dependencies\n');
    fprintf(fid, '- Financial Toolbox\n');
    fprintf(fid, '- Statistics and Machine Learning Toolbox\n');
    fprintf(fid, '- Deep Learning Toolbox\n');
    fprintf(fid, '- Text Analytics Toolbox\n');
    
    fclose(fid);
    
    disp('Generated PROJECT_STATISTICS.md successfully.');
end
